### ISSUE TITLE
设置监听事件导致无法轮播

### ISSUE THREAD

**Issue by huchenguang** [HaowenLee/TextBanner#1]
在adapter里写监听轮播布局的点击事件之后，   轮播会停止

**Comment by huchenguang** [comment]
class TextBannerAdapter(context: Context?, data: MutableList<NewsListBean.NewsList.News>?) :
    BaseAdapter<NewsListBean.NewsList.News>(context, data) {
    override fun onBindViewData(convertView: View, position: Int) {
        val news = getItem(position)
        val tvTipTitle: TextView = convertView.findViewById(R.id.tv_tip_title)
        val tvTipContent: TextView = convertView.findViewById(R.id.tv_tip_content)
        tvTipTitle.text = news.news_title
        tvTipContent.text = news.news_des
        /*convertView.setOnClickListener {
            mListener?.onItemClick(position)
        }*/
    }

    override fun onCreateView(parent: ViewGroup): View {
        return mInflater.inflate(R.layout.item_news_text_banner_header, parent, false)
    }

    var mListener: OnBannerItemClickListener? = null

    fun setOnBannerItemClickListener(listener: OnBannerItemClickListener) {
        this.mListener = listener
    }

    interface OnBannerItemClickListener {
        fun onItemClick(position: Int)
    }
}
类似这样写

**Comment by HaowenLee** [comment]
非常感谢你的问题反馈，原本考虑的是不涉及Item的点击事件。1.0.1 已经替换了定时的方式，将不会出现该问题。
